version: '3.8'
services:
    main:
        container_name: main
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - mysqlDB

    queue:
        container_name: queue
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on:
            - mysqlDB

    mysqlDB:
        image: mysql:8.0
        container_name: mysqlDB
        environment:
            MYSQL_DATABASE: ticketsystem
            MYSQL_USER: root
            MYSQL_ROOT: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
